name: 1.2.3 Программное избавление от дребезга

on:
  push:
    paths:
      - '123-led-button-debounce/**'
      - '.github/workflows/check-1-2-3.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ant-lab-ru/es-test/.github/workflows/check-1-2-3.yml@master
    secrets:
      ES_ACCOUNT_SECRET: ${{ secrets.ES_ACCOUNT_SECRET }}
